apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cinepass-microservices-monitor
  namespace: cinepass-dev
  labels:
    release: prometheus-stack
    app.kubernetes.io/part-of: cinepass
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - auth-service
          - catalog-service
          - booking-service
          - payment-service
          - notification-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
