apiVersion: v2
name: cinepass
description: CinePass Enterprise Cloud-Native Movie Ticketing Microservices Umbrella Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: CinePass DevOps Engineering
    email: devops@cinepass.com
