apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  labels:
    {{- include "cinepass.labels" . | nindent 4 }}
    app: auth-service
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.iamRoles.externalSecrets | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-service-sa
  labels:
    {{- include "cinepass.labels" . | nindent 4 }}
    app: catalog-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: booking-service-sa
  labels:
    {{- include "cinepass.labels" . | nindent 4 }}
    app: booking-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  labels:
    {{- include "cinepass.labels" . | nindent 4 }}
    app: payment-service
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.iamRoles.appServices | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  labels:
    {{- include "cinepass.labels" . | nindent 4 }}
    app: notification-service
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.iamRoles.appServices | quote }}
