apiVersion: v1
kind: ConfigMap
metadata:
  name: cinepass-config
  namespace: cinepass-dev
  labels:
    app.kubernetes.io/part-of: cinepass
    environment: dev
data:
  NODE_ENV: "production"
  AWS_REGION: "ap-south-2"
  
  # Database Non-Sensitive Endpoints
  DB_HOST: "cinepass-dev-postgres.chis0ucuosxf.ap-south-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "cinepass_db"
  DB_USER: "postgres"

  # Redis Non-Sensitive Endpoints
  REDIS_HOST: "cinepass-dev-redis-redis.wvth1k.0001.aps2.cache.amazonaws.com"
  REDIS_PORT: "6379"

  # CloudFront CDN & S3 Assets (Using regional S3 domain for Free-Tier)
  CLOUDFRONT_DOMAIN: "https://cinepass-assets-07784.s3.ap-south-2.amazonaws.com"
  S3_BUCKET_NAME: "cinepass-assets-07784"

  # AWS SQS Queues
  SQS_QUEUE_URL: "https://sqs.ap-south-2.amazonaws.com/304960798044/cinepass-dev-booking-queue"
  SQS_DLQ_URL: "https://sqs.ap-south-2.amazonaws.com/304960798044/cinepass-dev-booking-queue-dlq"

  # Microservices Internal Cluster Discovery Endpoints
  AUTH_SERVICE_URL: "http://auth-service:8080"
  CATALOG_SERVICE_URL: "http://catalog-service:8081"
  BOOKING_SERVICE_URL: "http://booking-service:8082"
  PAYMENT_SERVICE_URL: "http://payment-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"

  # Application Tuning
  SEAT_LOCK_TTL_SECONDS: "300"
