apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cinepass-aws-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cinepass-credentials-sync
  namespace: cinepass-dev
  labels:
    app.kubernetes.io/part-of: cinepass
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cinepass-aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: cinepass-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: cinepass/dev/credentials
        property: db_password
    - secretKey: JWT_SECRET
      remoteRef:
        key: cinepass/dev/credentials
        property: jwt_secret
