apiVersion: v1
kind: Secret
metadata:
  name: cinepass-credentials
  namespace: cinepass-dev
  labels:
    app.kubernetes.io/part-of: cinepass
type: Opaque
stringData:
  DB_PASSWORD: "CinePassDev2026Secure!"
  JWT_SECRET: "CinePassDevSecretKey2026SuperSecureJwtSigningKey!"
