apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinepass-dev

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 01-secret.yaml
  - 01-auth-service.yaml
  - 02-catalog-service.yaml
  - 03-booking-service.yaml
  - 04-payment-service.yaml
  - 05-notification-service.yaml
  - 06-ingress.yaml
  - 07-frontend-configmap.yaml
  - 07-frontend-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: cinepass
      environment: dev
    includeSelectors: false
